In [ ]:
# v1.0.0-dev

In [1]:
import pandas as pd
from pathlib import Path
import src.transformations.joining
import src.cdutils.database
import src.cdutils.caching
import src.transformations.calculations

In [3]:
data  = src.cdutils.database.fetch_data()

In [4]:
# wh_acctcommon = data['wh_acctcommon'].copy()

In [ ]:
cache_path = Path(r'Z:\Chad Projects\Ad Hoc Reports\Lee_Mason_Ins_Tracking\Production\assets\caching')
src.cdutils.caching.cache_data(cache_path, data)

Saved wh_acctcommon to Z:\Chad Projects\Ad Hoc Reports\Lee_Mason_Ins_Tracking\Production\assets\caching\wh_acctcommon.csv

In [2]:
# Access cached data
wh_acctcommon = pd.read_csv(Path(r'Z:\Chad Projects\Ad Hoc Reports\Lee_Mason_Ins_Tracking\Production\assets\caching\wh_acctcommon.csv'))
wh_acctloan = pd.read_csv(Path(r'Z:\Chad Projects\Ad Hoc Reports\Lee_Mason_Ins_Tracking\Production\assets\caching\wh_acctloan.csv'))
wh_loans = pd.read_csv(Path(r'Z:\Chad Projects\Ad Hoc Reports\Lee_Mason_Ins_Tracking\Production\assets\caching\wh_loans.csv'))
acctpropins = pd.read_csv(Path(r'Z:\Chad Projects\Ad Hoc Reports\Lee_Mason_Ins_Tracking\Production\assets\caching\acctpropins.csv'))
wh_prop = pd.read_csv(Path(r'Z:\Chad Projects\Ad Hoc Reports\Lee_Mason_Ins_Tracking\Production\assets\caching\wh_prop.csv'))
wh_prop2 = pd.read_csv(Path(r'Z:\Chad Projects\Ad Hoc Reports\Lee_Mason_Ins_Tracking\Production\assets\caching\wh_prop2.csv'))
acctloanlimithist = pd.read_csv(Path(r'Z:\Chad Projects\Ad Hoc Reports\Lee_Mason_Ins_Tracking\Production\assets\caching\acctloanlimithist.csv'))
wh_inspolicy = pd.read_csv(Path(r'Z:\Chad Projects\Ad Hoc Reports\Lee_Mason_Ins_Tracking\Production\assets\caching\wh_inspolicy.csv'))
persaddruse = pd.read_csv(Path(r'Z:\Chad Projects\Ad Hoc Reports\Lee_Mason_Ins_Tracking\Production\assets\caching\persaddruse.csv'))
orgaddruse = pd.read_csv(Path(r'Z:\Chad Projects\Ad Hoc Reports\Lee_Mason_Ins_Tracking\Production\assets\caching\orgaddruse.csv'))
wh_addr = pd.read_csv(Path(r'Z:\Chad Projects\Ad Hoc Reports\Lee_Mason_Ins_Tracking\Production\assets\caching\wh_addr.csv'))

In [3]:
orgaddruse.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15726 entries, 0 to 15725
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   orgnbr   15726 non-null  int64
 1   addrnbr  15726 non-null  int64
dtypes: int64(2)
memory usage: 245.8 KB

In [4]:
main_data = src.transformations.joining.join_loan_tables(wh_acctcommon, wh_acctloan, wh_loans)

In [5]:
prop_data = src.transformations.joining.join_prop_tables(wh_prop, wh_prop2)

In [6]:
main_data = src.transformations.joining.appending_owner_address(main_data, orgaddruse, persaddruse, wh_addr)

In [7]:
main_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7699 entries, 0 to 7698
Data columns (total 37 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   acctnbr              7699 non-null   int64
 1   effdate              7699 non-null   object
 2   ownersortname        7699 non-null   object
 3   notebal              7699 non-null   float64
 4   bookbalance          7699 non-null   float64
 5   mjaccttypcd          7699 non-null   object
 6   currmiaccttypcd      7699 non-null   object
 7   product              7699 non-null   object
 8   curracctstatcd       7699 non-null   object
 9   taxrptforpersnbr     4516 non-null   float64
 10  taxrptfororgnbr      3183 non-null   float64
 11  loanofficer          7699 non-null   object
 12  acctofficer          0 non-null      float64
 13  contractdate         7699 non-null   object
 14  noteopenamt          6775 non-null   float64
 15  noteintrate          7699 non-null   float64
 16  creditlimitamt       2643 non-null   float64
 17  origintrate          7042 non-null   float64
 18  marginfixed          7684 non-null   float64
 19  fdiccatcd            7068 non-null   object
 20  amortterm            7684 non-null   float64
 21  totalpctsold         7684 non-null   float64
 22  cobal                7684 non-null   float64
 23  credlimitclatresamt  7684 non-null   float64
 24  origdate             7489 non-null   object
 25  currterm             7684 non-null   float64
 26  loanidx              7684 non-null   object
 27  rcf                  2881 non-null   object
 28  availbalamt          2200 non-null   float64
 29  fdiccatdesc          7068 non-null   object
 30  addrnbr              7680 non-null   float64
 31  text1                7680 non-null   object
 32  text2                124 non-null    object
 33  text3                2 non-null      object
 34  cityname             7680 non-null   object
 35  statecd              7680 non-null   object
 36  zipcd                7680 non-null   float64
dtypes: float64(18), int64(1), object(18)
memory usage: 2.2+ MB

In [8]:
main_data = src.transformations.calculations.append_total_exposure_field(main_data)
main_data = src.transformations.calculations.cleaning_loan_data(main_data)

In [11]:
main_data

<class 'pandas.core.frame.DataFrame'>
Index: 23593 entries, 0 to 24202
Data columns (total 39 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   acctnbr                 23593 non-null  int64
 1   effdate                 23593 non-null  object
 2   ownersortname           23593 non-null  object
 3   nameaddr1               23593 non-null  object
 4   nameaddr2               23593 non-null  object
 5   primaryownercity        23575 non-null  object
 6   primaryownerstate       23575 non-null  object
 7   primaryownerzipcd       23575 non-null  float64
 8   notebal                 23593 non-null  float64
 9   bookbalance             23593 non-null  float64
 10  mjaccttypcd             23593 non-null  object
 11  currmiaccttypcd         23593 non-null  object
 12  curracctstatcd          23593 non-null  object
 13  taxrptforpersnbr        21020 non-null  float64
 14  taxrptfororgnbr         2573 non-null   float64
 15  loanofficer             23593 non-null  object
 16  acctofficer             0 non-null      float64
 17  contractdate            23593 non-null  object
 18  noteopenamt             23593 non-null  float64
 19  noteintrate             23593 non-null  float64
 20  creditlimitamt          23593 non-null  float64
 21  origintrate             23531 non-null  float64
 22  marginfixed             23593 non-null  float64
 23  fdiccatcd               23587 non-null  object
 24  amortterm               23593 non-null  int64
 25  totalpctsold            23593 non-null  float64
 26  cobal                   23593 non-null  float64
 27  credlimitclatresamt     23593 non-null  float64
 28  origdate                23587 non-null  datetime64[ns]
 29  currterm                23593 non-null  int64
 30  loanidx                 23581 non-null  object
 31  rcf                     2902 non-null   object
 32  availbalamt             23593 non-null  float64
 33  fdiccatdesc             23587 non-null  object
 34  Net Balance             23593 non-null  float64
 35  Net Available           23593 non-null  float64
 36  Net Collateral Reserve  23593 non-null  float64
 37  Total Exposure          23593 non-null  float64
 38  orig_ttl_loan_amt       23593 non-null  float64
dtypes: datetime64[ns](1), float64(20), int64(3), object(15)
memory usage: 7.2+ MB

In [12]:
acctpropins

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7960 entries, 0 to 7959
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   acctnbr               7960 non-null   int64
 1   propnbr               7960 non-null   int64
 2   intrpolicynbr         7960 non-null   int64
 3   effdate               7960 non-null   object
 4   inactivedate          2 non-null      object
 5   datelastmaint         7960 non-null   object
 6   escrowyn              7960 non-null   object
 7   lenderfundedyn        7960 non-null   object
 8   escdisbchangeeffdate  6916 non-null   object
dtypes: int64(3), object(6)
memory usage: 559.8+ KB

In [9]:
def consolidation_with_multiple_props(main_loan_data: pd.DataFrame, property_data: pd.DataFrame) -> pd.DataFrame:
    """
    This is the main_loan_data joined with property_data, including multiple properties per acctnbr.
    Keep in mind acctnbr field is not unique here.

    Args:
        main_loan_data (pd.DataFrame)
        property_data (pd.DataFrame)

    Returns:
        df (pd.DataFrame): df with multiple properties per acctnbr
    """
    # Pre-merge validation
    assert main_loan_data['acctnbr'].is_unique, "Duplicates exist"

    # Merge
    df = pd.merge(main_loan_data, property_data, on='acctnbr', how='left')
    return df

In [10]:
merged_data = src.transformations.joining.consolidation_with_multiple_props(main_data, prop_data)

In [35]:
merged_data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24930 entries, 0 to 24929
Data columns (total 49 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   acctnbr                 24930 non-null  int64
 1   effdate                 24930 non-null  object
 2   ownersortname           24930 non-null  object
 3   nameaddr1               24930 non-null  object
 4   nameaddr2               24930 non-null  object
 5   primaryownercity        24908 non-null  object
 6   primaryownerstate       24908 non-null  object
 7   primaryownerzipcd       24908 non-null  float64
 8   notebal                 24930 non-null  float64
 9   bookbalance             24930 non-null  float64
 10  mjaccttypcd             24930 non-null  object
 11  currmiaccttypcd         24930 non-null  object
 12  curracctstatcd          24930 non-null  object
 13  taxrptforpersnbr        21216 non-null  float64
 14  taxrptfororgnbr         3714 non-null   float64
 15  loanofficer             24930 non-null  object
 16  acctofficer             0 non-null      float64
 17  contractdate            24930 non-null  object
 18  noteopenamt             24930 non-null  float64
 19  noteintrate             24930 non-null  float64
 20  creditlimitamt          24930 non-null  float64
 21  origintrate             24866 non-null  float64
 22  marginfixed             24930 non-null  float64
 23  fdiccatcd               24921 non-null  object
 24  amortterm               24930 non-null  int64
 25  totalpctsold            24930 non-null  float64
 26  cobal                   24930 non-null  float64
 27  credlimitclatresamt     24930 non-null  float64
 28  origdate                24924 non-null  datetime64[ns]
 29  currterm                24930 non-null  int64
 30  loanidx                 24918 non-null  object
 31  rcf                     3899 non-null   object
 32  availbalamt             24930 non-null  float64
 33  fdiccatdesc             24921 non-null  object
 34  Net Balance             24930 non-null  float64
 35  Net Available           24930 non-null  float64
 36  Net Collateral Reserve  24930 non-null  float64
 37  Total Exposure          24930 non-null  float64
 38  orig_ttl_loan_amt       24930 non-null  float64
 39  propnbr                 24437 non-null  float64
 40  propaddr1               5956 non-null   object
 41  propaddr2               6 non-null      object
 42  propcity                5957 non-null   object
 43  propstate               5955 non-null   object
 44  propzip                 5944 non-null   float64
 45  aprsvalueamt            5457 non-null   float64
 46  aprsdate                5457 non-null   object
 47  proptypdesc             24437 non-null  object
 48  propdesc                24422 non-null  object
dtypes: datetime64[ns](1), float64(23), int64(3), object(22)
memory usage: 9.3+ MB

In [15]:
insurance_merged = src.transformations.joining.merging_insurance_tables(acctpropins, wh_inspolicy)

In [12]:
insurance_merged

,acctnbr,propnbr,intrpolicynbr,effdate_x,inactivedate_x,datelastmaint_x,escrowyn,lenderfundedyn,escdisbchangeeffdate,rundate,...,policydocnbr,inactivedate_y,firstmonthcd,duedaynbr,dueweekdaycd,coverageamt,firstyearnbr,refundableyn,instypdesc,datelastmaint_y
0,201342911,30221,4213,2019-05-01,NaN,2024-05-01 08:07:28,Y,N,2019-05-01,2025-01-28,...,NaN,NaN,5.0,1.0,NaN,567000.00,NaN,N,Homeowner's Insurance,2025-01-28 21:49:25
1,150426875,50221,5446,2020-02-05,NaN,2020-07-26 23:28:41,Y,N,2021-02-01,2025-01-28,...,NaN,NaN,2.0,1.0,NaN,350000.00,NaN,N,Homeowner's Insurance,2025-01-28 21:49:25
2,201754331,32082,5694,2020-03-11,NaN,2020-07-26 23:28:41,Y,N,2020-03-01,2025-01-28,...,NaN,NaN,1.0,1.0,NaN,NaN,NaN,N,Homeowner's Insurance,2025-01-28 21:49:25
3,150439381,50885,5697,2020-05-01,NaN,2023-02-13 10:53:20,Y,N,2020-05-01,2025-01-28,...,NaN,NaN,NaN,1.0,NaN,0.25,NaN,N,Private Mortgage Insurance,2025-01-28 21:49:25
4,150439381,50885,5698,2020-03-12,NaN,2024-12-17 14:41:00,N,N,2021-02-01,2025-01-28,...,NaN,2021-03-10,2.0,1.0,NaN,587000.00,NaN,N,Homeowner's Insurance,2025-01-28 21:49:25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7955,150741380,71134,10485,2022-05-02,NaN,2024-08-22 08:32:15,Y,N,2022-08-01,2025-01-28,...,NaN,NaN,8.0,1.0,NaN,503567.00,NaN,N,Homeowner's Insurance,2025-01-28 21:49:25
7956,150773896,73616,11646,2022-07-29,NaN,2024-06-18 12:13:48,Y,N,2023-07-01,2025-01-28,...,NaN,NaN,7.0,1.0,NaN,624000.00,NaN,N,Homeowner's Insurance,2025-01-28 21:49:25
7957,150243584,40256,11764,2022-08-15,NaN,2024-07-22 10:09:46,Y,N,2023-07-01,2025-01-28,...,NaN,NaN,7.0,1.0,NaN,500000.00,NaN,N,Homeowner's Insurance,2025-01-28 21:49:25
7958,201253881,29920,11807,2022-08-17,NaN,2024-08-20 08:24:20,Y,N,2023-08-01,2025-01-28,...,NaN,NaN,8.0,1.0,NaN,1199800.00,NaN,N,Homeowner's Insurance,2025-01-28 21:49:25
7959,150791161,74725,12084,2022-09-12,NaN,2024-08-29 08:16:43,Y,N,2023-08-01,2025-01-28,...,NaN,NaN,8.0,1.0,NaN,509000.00,NaN,N,Homeowner's Insurance,2025-01-28 21:49:25

In [ ]:
merged_data = src.transformations.joining.append_insurance_data_to_main(merged_data, insurance_merged)

In [19]:
merged_data

,acctnbr_x,effdate,ownersortname,notebal,bookbalance,mjaccttypcd,currmiaccttypcd,product,curracctstatcd,taxrptforpersnbr,...,policydocnbr,inactivedate_y,firstmonthcd,duedaynbr,dueweekdaycd,coverageamt,firstyearnbr,refundableyn,instypdesc,datelastmaint_y
0,6253391,2025-01-30,FROM THE BAY INC,45710.06,45710.06,CML,CM40,Commercial Mortgages,ACT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6253411,2025-01-30,FRIENDSHIP REALTY GROUP,491651.90,491651.90,CML,CM40,Commercial Mortgages,ACT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6253501,2025-01-30,THE ARC OF BRISTOL COUNTY INC,1789910.19,1789910.19,CML,CM45,Tax Exempt Bonds,ACT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6253601,2025-01-30,"MEDEIROS, JOSE M.",61074.40,61074.40,CML,CM40,Commercial Mortgages,ACT,1031288.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6253601,2025-01-30,"MEDEIROS, JOSE M.",61074.40,61074.40,CML,CM40,Commercial Mortgages,ACT,1031288.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9952,150481192,2025-01-30,"BROWN, JASON P.",604024.41,604024.41,MTG,MG25,25 Year Fixed Rate,ACT,1114824.0,...,NaN,NaN,6.0,1.0,NaN,1908000.00,NaN,N,Homeowner's Insurance,2025-01-28 21:49:25
9953,150642421,2025-01-30,"SHARLAND, ROBERT M.",364142.99,364142.99,MTG,MG29,30 Year Fixed Rate,ACT,1042737.0,...,NaN,NaN,4.0,1.0,NaN,567000.00,NaN,N,Homeowner's Insurance,2025-01-28 21:49:25
9954,150642421,2025-01-30,"SHARLAND, ROBERT M.",364142.99,364142.99,MTG,MG29,30 Year Fixed Rate,ACT,1042737.0,...,NaN,2023-06-05,NaN,1.0,NaN,0.25,NaN,N,Private Mortgage Insurance,2025-01-28 21:49:25
9955,150642421,2025-01-30,"SHARLAND, ROBERT M.",364142.99,364142.99,MTG,MG29,30 Year Fixed Rate,ACT,1042737.0,...,NaN,2022-04-25,8.0,1.0,NaN,450000.00,NaN,N,Homeowner's Insurance,2025-01-28 21:49:25
9956,151130772,2025-01-30,WM3 PROPERTIES LLC,998797.62,0.00,CML,CM77,ARC Fixed Loan,ACT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Write out to excel
output_path = Path(r'Z:\Chad Projects\Ad Hoc Reports\Lee_Mason_Ins_Tracking\Production\output')
merged_data.to_excel(output_path, engine='openpyxl')

Effective end, until feedback & tweaks

In [36]:
acctpropins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7960 entries, 0 to 7959
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   acctnbr               7960 non-null   int64
 1   propnbr               7960 non-null   int64
 2   intrpolicynbr         7960 non-null   int64
 3   effdate               7960 non-null   object
 4   inactivedate          2 non-null      object
 5   datelastmaint         7960 non-null   object
 6   escrowyn              7960 non-null   object
 7   lenderfundedyn        7960 non-null   object
 8   escdisbchangeeffdate  6916 non-null   object
dtypes: int64(3), object(6)
memory usage: 559.8+ KB

In [37]:
assert acctpropins['acctnbr'].is_unique, "Duplicates found"

AssertionError: Duplicates found

In [38]:
assert acctpropins['propnbr'].is_unique, "Duplicates found"

AssertionError: Duplicates found

In [39]:
acctpropins.head()

,acctnbr,propnbr,intrpolicynbr,effdate,inactivedate,datelastmaint,escrowyn,lenderfundedyn,escdisbchangeeffdate
0,201342911,30221,4213,2019-05-01,NaN,2024-05-01 08:07:28,Y,N,2019-05-01
1,150426875,50221,5446,2020-02-05,NaN,2020-07-26 23:28:41,Y,N,2021-02-01
2,201754331,32082,5694,2020-03-11,NaN,2020-07-26 23:28:41,Y,N,2020-03-01
3,150439381,50885,5697,2020-05-01,NaN,2023-02-13 10:53:20,Y,N,2020-05-01
4,150439381,50885,5698,2020-03-12,NaN,2024-12-17 14:41:00,N,N,2021-02-01

In [40]:
wh_inspolicy = pd.read_csv(Path(r'Z:\Chad Projects\Ad Hoc Reports\Lee_Mason_Ins_Tracking\Production\assets\caching\wh_inspolicy.csv'))

In [41]:
wh_inspolicy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7957 entries, 0 to 7956
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   intrpolicynbr    7957 non-null   int64
 1   rundate          7957 non-null   object
 2   insorgnbr        7957 non-null   int64
 3   instypcd         7957 non-null   object
 4   extpolicynbr     7957 non-null   object
 5   agentorgnbr      4 non-null      float64
 6   premcalperiodcd  7944 non-null   object
 7   premamt          7944 non-null   float64
 8   effdate          7957 non-null   object
 9   expiredate       7466 non-null   object
 10  policydocnbr     0 non-null      float64
 11  inactivedate     1695 non-null   object
 12  firstmonthcd     7353 non-null   float64
 13  duedaynbr        7937 non-null   float64
 14  dueweekdaycd     0 non-null      float64
 15  coverageamt      7495 non-null   float64
 16  firstyearnbr     0 non-null      float64
 17  refundableyn     7957 non-null   object
 18  instypdesc       7957 non-null   object
 19  datelastmaint    7957 non-null   object
dtypes: float64(8), int64(2), object(10)
memory usage: 1.2+ MB

In [42]:
wh_inspolicy.head()

,intrpolicynbr,rundate,insorgnbr,instypcd,extpolicynbr,agentorgnbr,premcalperiodcd,premamt,effdate,expiredate,policydocnbr,inactivedate,firstmonthcd,duedaynbr,dueweekdaycd,coverageamt,firstyearnbr,refundableyn,instypdesc,datelastmaint
0,2756,2025-01-28,1114,HOME,002235290-95A,NaN,ANNU,1049.37,2011-09-30,2027-11-01,NaN,NaN,6.0,1.0,NaN,450000.0,NaN,N,Homeowner's Insurance,2025-01-28 21:49:25
1,2757,2025-01-28,1132,HOME,HP3 W956054,NaN,ANNU,541.00,2011-09-30,2041-10-01,NaN,2024-09-30,9.0,1.0,NaN,0.0,NaN,N,Homeowner's Insurance,2025-01-28 21:49:25
2,2758,2025-01-28,1097,HOME,8500049395,NaN,ANNU,1.00,2011-09-30,2041-10-01,NaN,NaN,10.0,1.0,NaN,1000000.0,NaN,N,Homeowner's Insurance,2025-01-28 21:49:25
3,2759,2025-01-28,1097,HOME,8500049395,NaN,ANNU,1.00,2011-09-30,2041-10-01,NaN,NaN,10.0,1.0,NaN,11170000.0,NaN,N,Homeowner's Insurance,2025-01-28 21:49:25
4,2760,2025-01-28,1097,HOME,BCYMLH,NaN,ANNU,0.01,2011-10-11,2031-11-01,NaN,NaN,11.0,1.0,NaN,292000.0,NaN,N,Homeowner's Insurance,2025-01-28 21:49:25

In [43]:
wh_inspolicy['instypcd'].unique()

array(['HOME', 'FLOD', 'PMI', 'FPLC', 'BRSK', 'LIAB', 'COML', 'CNDO',
       'FORP'], dtype=object)

In [44]:
assert wh_inspolicy['intrpolicynbr'].is_unique, "Duplicates"