In [1]:
## Memorializing this as the easy way to lookup accounts

In [1]:
"""
Main Entry Point
"""
from pathlib import Path
from typing import List
import argparse
from datetime import datetime

import pandas as pd # type: ignore

import src.fetch_data # type: ignore
import src.core_transform # type: ignore
import cdutils.pkey_sqlite # type: ignore
import cdutils.hhnbr # type: ignore


old_data = src.fetch_data.fetch_data_2024()
new_data = src.fetch_data.fetch_data_2025()

# # # Core transformation pipeline
old_data = src.core_transform.main_pipeline(old_data)
new_data = src.core_transform.main_pipeline(new_data)

# Raw data with pkey appended
old_data = cdutils.pkey_sqlite.add_pkey(old_data)
new_data = cdutils.pkey_sqlite.add_pkey(new_data)

In [2]:
old_data

,effdate,acctnbr,ownersortname,product,noteopenamt,ratetypcd,mjaccttypcd,currmiaccttypcd,curracctstatcd,noteintrate,...,availbalamt,fdiccatdesc,origbal,loanlimityn,Net Balance,Net Available,Net Collateral Reserve,Total Exposure,orig_ttl_loan_amt,portfolio_key
0,2024-12-31,150586025,GREATER FALL RIVER V.S.D,Municipal Now,0.0,VAR,CK,CK27,ACT,0.0003,...,0.0,NaN,NaN,NaN,34519570.46,0.0,0.0,34519570.46,0.0,41253
1,2024-12-31,150847394,COUNTY OF BRISTOL,Municipal Money Market,0.0,VAR,CK,CK18,ACT,0.0350,...,0.0,NaN,NaN,NaN,28357563.33,0.0,0.0,28357563.33,0.0,4335
2,2024-12-31,150887241,CITY OF TAUNTON,ICS Shadow - Muni - MMDA/SAV,0.0,None,CK,CK42,ACT,0.0000,...,0.0,NaN,NaN,NaN,19049635.93,0.0,0.0,19049635.93,0.0,4309
3,2024-12-31,7100515,COMMONWEALTH OF MASSACHUSETTS,3 Month LIBOR CD,0.0,FIX,TD,CD09,ACT,0.0000,...,0.0,NaN,NaN,NaN,15000000.00,0.0,0.0,15000000.00,0.0,4961
4,2024-12-31,150988429,CITY OF ATTLEBORO,ICS Shadow - Muni - Demand,0.0,None,CK,CK36,ACT,0.0000,...,0.0,NaN,NaN,NaN,14899210.72,0.0,0.0,14899210.72,0.0,5357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62833,2024-12-31,27044963,HILLER COMPANY INC,Business Checking,0.0,None,CK,CK12,ACT,0.0000,...,0.0,NaN,NaN,NaN,-1665.79,0.0,0.0,-1665.79,0.0,39653
62834,2024-12-31,26230194,"ROSE, ANTHONY D.",Prime Time Checking,0.0,VAR,CK,CK06,ACT,0.0003,...,0.0,NaN,NaN,NaN,-1872.68,0.0,0.0,-1872.68,0.0,36536
62835,2024-12-31,27047237,FIRST AUTOMOTIVE GROUP INC,Business Checking,0.0,None,CK,CK12,ACT,0.0000,...,0.0,NaN,NaN,NaN,-2491.78,0.0,0.0,-2491.78,0.0,3840
62836,2024-12-31,151116235,FTRF 143 INC,Simple Business Checking,500.0,None,CK,CK25,ACT,0.0000,...,0.0,NaN,NaN,NaN,-7038.87,0.0,0.0,-7038.87,500.0,82264
62837,2024-12-31,150337783,BRISTOL COUNTY SAVINGS BANK,Business Checking,0.0,None,CK,CK12,ACT,0.0000,...,0.0,NaN,NaN,NaN,-257128.42,0.0,0.0,-257128.42,0.0,1293

In [3]:
new_data

,effdate,acctnbr,ownersortname,product,noteopenamt,ratetypcd,mjaccttypcd,currmiaccttypcd,curracctstatcd,noteintrate,...,availbalamt,fdiccatdesc,origbal,loanlimityn,Net Balance,Net Available,Net Collateral Reserve,Total Exposure,orig_ttl_loan_amt,portfolio_key
0,2025-03-31,150887241,CITY OF TAUNTON,ICS Shadow - Muni - MMDA/SAV,0.00,None,CK,CK42,ACT,0.0000,...,0.0,NaN,NaN,NaN,31310568.38,0.0,0.0,31310568.38,0.00,4309
1,2025-03-31,150847394,COUNTY OF BRISTOL,Municipal Money Market,0.00,VAR,CK,CK18,ACT,0.0350,...,0.0,NaN,NaN,NaN,23560204.27,0.0,0.0,23560204.27,0.00,4335
2,2025-03-31,150586025,GREATER FALL RIVER V.S.D,Municipal Now,0.00,VAR,CK,CK27,ACT,0.0003,...,0.0,NaN,NaN,NaN,22406466.38,0.0,0.0,22406466.38,0.00,41253
3,2025-03-31,60801557,"COMMUNITY COUNSELING OF BRISTOL COUNTY, INCORP...",Investment Business Checking,0.00,VAR,CK,CK28,ACT,0.0220,...,0.0,NaN,NaN,NaN,22383656.79,0.0,0.0,22383656.79,0.00,3652
4,2025-03-31,150988429,CITY OF ATTLEBORO,ICS Shadow - Muni - Demand,0.00,None,CK,CK36,ACT,0.0000,...,0.0,NaN,NaN,NaN,19616693.16,0.0,0.0,19616693.16,0.00,5357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62768,2025-03-31,151087949,"LEVASSEUR, SHAYLEE A.",Basic Checking,11.61,None,CK,CK02,ACT,0.0000,...,0.0,NaN,NaN,NaN,-832.50,0.0,0.0,-832.50,11.61,56974
62769,2025-03-31,151104321,"LADOUCEUR, CHERYL A.",NOW Checking,12149.95,VAR,CK,CK05,ACT,0.0003,...,0.0,NaN,NaN,NaN,-835.30,0.0,0.0,-835.30,12149.95,81859
62770,2025-03-31,151072370,"TIMMS, RUSSELL E.",Basic Checking,1500.00,None,CK,CK02,ACT,0.0000,...,0.0,NaN,NaN,NaN,-843.00,0.0,0.0,-843.00,1500.00,1535
62771,2025-03-31,101756,"COLANGELO, STEVEN J.",BCSB High Yield Checking,0.00,VAR,CK,CK35,ACT,0.0005,...,0.0,NaN,NaN,NaN,-3663.44,0.0,0.0,-3663.44,0.00,151
62772,2025-03-31,150337783,BRISTOL COUNTY SAVINGS BANK,Business Checking,0.00,None,CK,CK12,ACT,0.0000,...,0.0,NaN,NaN,NaN,-551825.49,0.0,0.0,-551825.49,0.00,1293

In [ ]:
old_unique = old_data.groupby('branchname')['portfolio_key'].nunique().sort_values(ascending=False).reset_index()

In [9]:
new_unique = new_data.groupby('branchname')['portfolio_key'].nunique().sort_values(ascending=False).reset_index()

In [19]:
consolidation_unique = pd.merge(old_unique, new_unique, how='outer', on='branchname')

In [20]:
consolidation_unique.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   branchname       38 non-null     object
 1   portfolio_key_x  38 non-null     int64
 2   portfolio_key_y  37 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.0+ KB

In [21]:
consolidation_unique_schema = {'portfolio_key_x':'float'}
consolidation_unique = cdutils.input_cleansing.enforce_schema(consolidation_unique, consolidation_unique_schema)

In [22]:
consolidation_unique = consolidation_unique.rename(columns={'portfolio_key_x': '2024_Q4','portfolio_key_y':'2025_Q1'}).copy()

In [23]:
consolidation_unique['change'] = consolidation_unique['2025_Q1'] - consolidation_unique['2024_Q4']

In [25]:
consolidation_unique['pct_change'] = (consolidation_unique['2025_Q1'] - consolidation_unique['2024_Q4']) / consolidation_unique['2024_Q4']

In [ ]:
consolidation_unique