In [14]:
from pathlib import Path
from typing import List

import pandas as pd

import src.cdutils.database
import src.cdutils.input_cleansing

In [15]:
data_nov23 = src.cdutils.database.fetch_data_nov23()
data_dec24 = src.cdutils.database.fetch_data_dec24()

In [16]:
data_nov23 = data_nov23['acctcommon'].copy()
data_dec24 = data_dec24['acctcommon'].copy()

In [17]:
data_nov23

,acctnbr,effdate,mjaccttypcd,product,currmiaccttypcd,bookbalance,acctofficer,ownersortname,curracctstatcd,contractdate,branchname,noteintrate,primaryownercity,primaryownerstate
0,100953,2023-11-01,TD,IRA >12 Month CmpDly CD,IR99,75373.57,TIFFANY J. CAHILL,"SABATINI, SYLVIA E.",ACT,2002-10-08,BCSB - GREENVILLE,0.0144,GREENVILLE,RI
1,101709,2023-11-01,SAV,Statement Savings,SV02,951.72,SHAQUITA L. WILSON,"PIANKA, CORI L.",ACT,2005-09-09,BCSB - CUMBERLAND,0.0005,GREENVILLE,RI
2,101730,2023-11-01,CK,Simple Business Checking,CK25,245.76,TIFFANY J. CAHILL,EXCITE! DANCE COMPANY,ACT,2004-03-09,BCSB - GREENVILLE,0,Chepachet,RI
3,101746,2023-11-01,CK,eChecking (18 & over),CK04,424.44,TIFFANY J. CAHILL,"TURNER, SHANYN N.",ACT,2004-03-16,BCSB - GREENVILLE,0,SMITHFIELD,RI
4,100170,2023-11-01,CK,Simple Business Checking,CK25,149.48,TIFFANY J. CAHILL,"BERNSTEIN, WILLIAM L.",ACT,2002-02-06,BCSB - GREENVILLE,0,CHEPACHET,RI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60422,150965857,2023-11-01,CK,Prime Time Checking,CK06,11288.5,Justin A. Jeffrey,"Johnson, Andrea K.",ACT,2023-10-27,BCSB - DARTMOUTH BRANCH,0.0005,South Dartmouth,MA
60423,4409408,2023-11-01,SAV,Statement Savings,SV02,1564.89,JACQUELINE A. THEIS,"GALLOWAY, SARAH M.",ACT,2010-03-10,BCSB - MAIN OFFICE,0.0005,TAUNTON,MA
60424,150781724,2023-11-01,CK,NOW Checking,CK05,123.01,SUSAN M. FARLEY,"STRINGER, JAMES E. II",ACT,2022-08-08,BCSB - NORTH RAYNHAM BRANCH,0.0003,NEW BEDFORD,MA
60425,150781732,2023-11-01,CK,Simple Business Checking,CK25,172.6,Justin A. Jeffrey,CUP OF JO JOS COFFEE LLC,ACT,2022-08-08,BCSB - DARTMOUTH BRANCH,0,South Dartmouth,MA
60426,150781766,2023-11-01,CK,Prime Time Elite Money Market,CK11,2070.68,AMY M. BRIGGS,"SANSON, RUSSELL L.",ACT,2022-08-08,BCSB - RAYNHAM CENTER BRANCH,0.0035,RAYNHAM,MA

In [18]:
data_dec24

,acctnbr,effdate,mjaccttypcd,product,currmiaccttypcd,bookbalance,acctofficer,ownersortname,curracctstatcd,contractdate,branchname,noteintrate,primaryownercity,primaryownerstate
0,151022408,2024-12-31,CK,Municipal Now,CK27,2500.59,JOHN G. DUGGAN,TOWN OF WESTBOROUGH,ACT,2024-03-19,BCSB - MUNI MAIN OFFICE,0.0003,WESTBOROUGH,MA
1,4465022727,2024-12-31,SAV,Statement Savings,SV02,5.4,SANDRA J. VANDETTE,"DONLEY, LUCILLE",ACT,2013-05-13,BCSB - NO ATTLEBORO BRANCH,0.0005,NORTH ATTLEBORO,MA
2,150871096,2024-12-31,CK,Prime Time Checking,CK06,9642.13,SANDRA J. VANDETTE,"JOHNSON, JEANNE M.",ACT,2023-03-16,BCSB - NO ATTLEBORO BRANCH,0.0005,ATTLEBORO,MA
3,4465001622,2024-12-31,SAV,Statement Savings,SV02,1687.47,SANDRA J. VANDETTE,"SANTOES, DAVID J.",ACT,2014-06-30,BCSB - NO ATTLEBORO BRANCH,0.0005,ATTLEBORO FALLS,MA
4,9011706,2024-12-31,TD,5 Year IRA CD,IR20,6299.22,JACQUELINE A. THEIS,"GRISWOLD, CYNTHIA M.",ACT,2014-07-21,BCSB - MAIN OFFICE,0.035,TAUNTON,MA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62833,150985540,2024-12-31,TD,9 Month Prime Time CD,CD23,39942.9,KAITLYN M. SILVA,"FOSTER, ALBERT JR",ACT,2023-12-19,BCSB - EAST FREETOWN BRANCH,0.0395,E FREETOWN,MA
62834,150978462,2024-12-31,CK,eChecking (18 & over),CK04,286.22,KAITLYN M. SILVA,"THOMPSON, MERION W.",ACT,2023-11-30,BCSB - EAST FREETOWN BRANCH,0,ROCHESTER,MA
62835,150987380,2024-12-31,TD,1 Year Prime Time CD,CD68,156903.9,KAITLYN M. SILVA,"FOSTER, DONALD A.",ACT,2023-12-27,BCSB - EAST FREETOWN BRANCH,0.04,LAKEVILLE,MA
62836,151055384,2024-12-31,CK,Business Checking,CK12,130.44,KEVIN M. MCCARTHY,NB PARTNERS FUND IV REIT LLC,ACT,2024-05-28,BCSB - MAIN OFFICE,0,WAKEFIELD,MA
62837,150998808,2024-12-31,TD,5 Year Prime Time IRA CD,IR22,16072.21,MOBOLAJI OMISORE,"BLANCHETTE, ROBERT W.",ACT,2024-01-25,BCSB - PAWTUCKET BRANCH,0.04,PAWTUCKET,RI

In [4]:

schema = {
    'noteintrate': float,
    'bookbalance': float
}

In [5]:
data_nov23 = src.cdutils.input_cleansing.enforce_schema(data_nov23, schema).copy()
data_dec24 = src.cdutils.input_cleansing.enforce_schema(data_dec24, schema).copy()

In [6]:
from typing import Dict

In [7]:
def generate_officer_df(data: pd.DataFrame) -> pd.DataFrame:
    """
    Group officers and sum balance
    """
    df = data.groupby('acctofficer')['bookbalance'].sum().reset_index()
    return df

In [8]:
data_nov23 = generate_officer_df(data_nov23)
data_dec24 = generate_officer_df(data_dec24)

In [9]:
data_nov23

                    acctofficer   bookbalance
0              ALISSA ERIN HALL  3.981335e+07
1                 AMY M. BRIGGS  1.450971e+08
2                      AN T. LE  3.581364e+07
3                ANDREW J. OMER  7.716564e+07
4            ANDREW K. SPRINGER  2.043580e+07
5           ANGELEBETH H. FARIA  4.650884e+07
6                  Amman Haidri  2.982412e+07
7                 BRIAN MCMAHON  1.885757e+05
8               Brandon Cannata  1.358582e+07
9          CHRISTINE M. PAREDES  3.135288e+07
10               DAMON T. ARPIN  1.300324e+07
11             DEBORAH J. KIRBY  1.364097e+05
12              DENNIS F. LEAHY  1.000000e+07
13            DONNA M. OLIVEIRA  8.629390e+03
14               David Ferreira  7.417720e+03
15             FRANK P. WILHELM  1.290750e+08
16            GEORGE J. MENDROS  2.839781e+06
17                 HASAN S. ALI  8.856437e+05
18              HUMAN RESOURCES  1.305343e+07
19  INTERNAL ACCOUNTS DIRECTORS  7.815127e+07
20          JACQUELINE A. THEIS  1.949692e+08
21              JANICE M. ALDEN  5.524138e+04
22             JEFFREY M. VIALL  4.023444e+07
23          JEFFREY P. PAGLIUCA  8.006010e+07
24             JOAN M. MEDEIROS  8.059142e+06
25               JOHN G. DUGGAN  9.012443e+07
26            Justin A. Jeffrey  7.542751e+07
27            KERI ANN KREYSSIG  0.000000e+00
28            KEVIN M. MCCARTHY  5.885496e+07
29               LAURA A. STACK  1.764116e+07
30           LINDA A. STERNFELT  2.668510e+03
31             LISA A. LASSITER  1.968340e+04
32              MARK A. BORKMAN  3.431988e+07
33              MARLENE C. LIRA  5.188497e+07
34                  MICHAEL HEY  1.612416e+08
35           MICHAEL P. PATACAO  1.852602e+07
36             MOBOLAJI OMISORE  4.482002e+07
37            MONICA A. FURTADO  3.069213e+07
38            NANCY F. PIMENTEL  0.000000e+00
39           NICOLE E. BOSWORTH -1.499000e+01
40              PAUL A. CAMILLE  1.410155e+07
41                PETER ST JEAN  1.132901e+06
42                PHALLINE SVAY  3.000023e+05
43             RICHARD D. TERRY  2.118874e+04
44             RICHARD J. CLARK  1.078515e+08
45              ROGER A. CABRAL  4.752559e+07
46           SANDRA J. VANDETTE  1.219248e+08
47           SHAQUITA L. WILSON  2.085300e+07
48               STACIE A. LONG  4.778182e+08
49              SUSAN M. FARLEY  1.043370e+08
50              THOMAS D. KELLY  1.085428e+07
51            TIFFANY J. CAHILL  3.413800e+07
52         WILLITTS S. MENDONCA  2.840652e+07

In [10]:
data_dec24

                    acctofficer   bookbalance
0                ALISSA E. HALL  4.918030e+07
1               AMMAN A. HAIDRI  1.763586e+07
2                AMY L. LECUYER  8.000000e+00
3                 AMY M. BRIGGS  1.432242e+08
4                      AN T. LE  3.092657e+07
5                ANDREW J. OMER  3.369869e+07
6              ANDREW RODRIGUES  7.120282e+06
7           ANGELEBETH H. FARIA  1.462845e+05
8               BRANDON CANNATA  1.713632e+07
9                 BRIAN MCMAHON  1.819824e+05
10         CHRISTINE M. PAREDES  3.758841e+07
11               DAMON T. ARPIN  4.049075e+07
12               DAVID FERREIRA  3.005227e+06
13             DEBORAH J. KIRBY  1.014172e+04
14              DENNIS F. LEAHY  1.500000e+07
15            DONNA M. OLIVEIRA  7.509020e+03
16             FRANK P. WILHELM  1.478801e+08
17            GEORGE J. MENDROS  3.572600e+07
18                 HASAN S. ALI  7.524487e+05
19                HOWARD HIMMEL  3.429482e+06
20              HUMAN RESOURCES  1.329922e+07
21  INTERNAL ACCOUNTS DIRECTORS  4.098748e+07
22          JACQUELINE A. THEIS  1.993638e+08
23              JANICE M. ALDEN  5.103013e+04
24             JEFFREY M. VIALL  5.291289e+07
25          JEFFREY P. PAGLIUCA  9.516129e+06
26             JOAN M. MEDEIROS  5.081681e+06
27               JOHN G. DUGGAN  9.438419e+07
28             JOSHUA A. CAMARA  2.386065e+07
29            JUSTIN A. JEFFREY  1.015788e+08
30             KAITLYN M. SILVA  5.692547e+07
31              KELLY ABERNATHY  0.000000e+00
32            KEVIN M. MCCARTHY  6.346275e+07
33               LAURA A. STACK  3.602477e+06
34           LINDA A. STERNFELT  2.670870e+03
35             LINDA M. WANLESS  4.000000e+01
36              MARK A. BORKMAN  3.188073e+07
37              MARLENE C. LIRA  5.804218e+07
38               MICHAEL A. HEY  1.593739e+08
39             MICHAEL PETERSON  4.253560e+03
40             MOBOLAJI OMISORE  4.775164e+07
41            MONICA A. FURTADO  2.861462e+07
42            NANCY F. PIMENTEL  4.000000e+03
43              NANCY P. CABRAL  6.146562e+06
44           NICOLE E. BOSWORTH  0.000000e+00
45              PAUL A. CAMILLE  9.031472e+06
46                PETER ST JEAN  3.948466e+05
47                PHALLINE SVAY  3.357941e+07
48             RICHARD D. TERRY  2.547822e+04
49             RICHARD J. CLARK  1.222703e+08
50              ROGER A. CABRAL  4.278956e+07
51           SANDRA J. VANDETTE  1.357031e+08
52                 SIRA SALGADO  7.986000e+04
53               STACIE A. LONG  3.734987e+08
54              SUSAN M. FARLEY  1.070948e+08
55              THOMAS D. KELLY  7.553579e+06
56            TIFFANY J. CAHILL  2.942059e+07
57         WILLITTS S. MENDONCA  6.723223e+07

In [11]:
merged_df = pd.merge(data_nov23, data_dec24, on='acctofficer', how='outer', suffixes=['_nov23','_dec24'])

In [ ]:
merged_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69 entries, 0 to 68
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   acctofficer        69 non-null     object
 1   bookbalance_nov23  53 non-null     float64
 2   bookbalance_dec24  58 non-null     float64
dtypes: float64(2), object(1)
memory usage: 1.7+ KB

In [3]:
acctcommon = data['acctcommon'].copy()

In [4]:
acctcommon

,acctnbr,effdate,mjaccttypcd,product,currmiaccttypcd,bookbalance,acctofficer,ownersortname,curracctstatcd,contractdate,branchname,noteintrate,primaryownercity,primaryownerstate
0,151022408,2024-12-31,CK,Municipal Now,CK27,2500.59,JOHN G. DUGGAN,TOWN OF WESTBOROUGH,ACT,2024-03-19,BCSB - MUNI MAIN OFFICE,0.0003,WESTBOROUGH,MA
1,151045830,2024-12-31,CK,eChecking (18 & over),CK04,363.35,MICHAEL A. HEY,"CARLINE, JILL K.",ACT,2024-05-05,BCSB - ATTLEBORO BRANCH,0,ATTLEBORO,MA
2,151042464,2024-12-31,CK,Money Market Statement,CK08,287.29,JUSTIN A. JEFFREY,"DUARTE, PATRICIA D.",ACT,2024-04-26,BCSB - DARTMOUTH BRANCH,0.0006,DARTMOUTH,MA
3,151041531,2024-12-31,TD,6 Month Business CD,CD17,717404.37,ALISSA E. HALL,THE ARC OF BRISTOL COUNTY INC,ACT,2024-04-25,BCSB - ATTLEBORO BRANCH,0.045,ATTLEBORO,MA
4,151036574,2024-12-31,CK,NOW Checking,CK05,164.62,SANDRA J. VANDETTE,"DONLEY, KEVIN B.",ACT,2024-04-15,BCSB - NO ATTLEBORO BRANCH,0.0003,NORTH ATTLEBORO,MA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8375,150985540,2024-12-31,TD,9 Month Prime Time CD,CD23,39942.9,KAITLYN M. SILVA,"FOSTER, ALBERT JR",ACT,2023-12-19,BCSB - EAST FREETOWN BRANCH,0.0395,E FREETOWN,MA
8376,150978462,2024-12-31,CK,eChecking (18 & over),CK04,286.22,KAITLYN M. SILVA,"THOMPSON, MERION W.",ACT,2023-11-30,BCSB - EAST FREETOWN BRANCH,0,ROCHESTER,MA
8377,150987380,2024-12-31,TD,1 Year Prime Time CD,CD68,156903.9,KAITLYN M. SILVA,"FOSTER, DONALD A.",ACT,2023-12-27,BCSB - EAST FREETOWN BRANCH,0.04,LAKEVILLE,MA
8378,151055384,2024-12-31,CK,Business Checking,CK12,130.44,KEVIN M. MCCARTHY,NB PARTNERS FUND IV REIT LLC,ACT,2024-05-28,BCSB - MAIN OFFICE,0,WAKEFIELD,MA
8379,150998808,2024-12-31,TD,5 Year Prime Time IRA CD,IR22,16072.21,MOBOLAJI OMISORE,"BLANCHETTE, ROBERT W.",ACT,2024-01-25,BCSB - PAWTUCKET BRANCH,0.04,PAWTUCKET,RI

In [ ]:
grouped_minors = acctcommon.groupby('currmiaccttypcd')['product'].first()

In [ ]:
grouped_minors

In [ ]:
minors = [
    'CK24', # 1st Business Checking
    'CK12', # Business Checking
    'CK25', # Simple Business Checking
    'CK30', # Business Elite Money Market
    'CK19', # Business Money Market
    'CK22', # Business Premium Plus MoneyMkt
    'CK23', # Premium Business Checking
    'CK40', # Community Assoc Reserve
    'CD67', # Commercial Negotiated Rate
    'CD01', # 1 Month Business CD
    'CD07', # 3 Month Business CD
    'CD17', # 6 Month Business CD
    'CD31', # 1 Year Business CD
    'CD35', # 1 Year Business CD
    'CD37', # 18 Month Business CD
    'CD38', # 2 Year Business CD
    'CD50', # 3 Year Business CD
    'CD53', # 4 Year Business CD
    'CD59', # 5 Year Business CD
    'CD76', # 9 Month Business CD
    'CD84', # 15 Month Business CD
    'CD95', # Business <12 Month Simple CD
    'CD96', # Business >12 Month Simple CD
    'CK28', # Investment Business Checking
    'CK33', # Specialty Business Checking
    'CK34', # ICS Shadow - Business - Demand
    'SV06' # Business Select High Yield
]

In [15]:
def filter_to_business_deposits(df: pd.DataFrame, minors: List) -> pd.DataFrame:
    """
    Filter the total deposit account dataset to specific business minors
    """
    df = df[df['currmiaccttypcd'].isin(minors)].copy()
    return df

In [16]:
df_filtered = filter_to_business_deposits(acctcommon, minors)

In [21]:
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 944 entries, 3365 to 6542
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   acctnbr            944 non-null    int64
 1   effdate            944 non-null    datetime64[ns]
 2   mjaccttypcd        944 non-null    object
 3   product            944 non-null    object
 4   currmiaccttypcd    944 non-null    object
 5   bookbalance        944 non-null    object
 6   acctofficer        940 non-null    object
 7   ownersortname      944 non-null    object
 8   curracctstatcd     944 non-null    object
 9   contractdate       944 non-null    datetime64[ns]
 10  branchname         944 non-null    object
 11  noteintrate        944 non-null    object
 12  primaryownercity   944 non-null    object
 13  primaryownerstate  944 non-null    object
dtypes: datetime64[ns](2), int64(1), object(11)
memory usage: 110.6+ KB

In [17]:
df_filtered['product'].unique()

array(['6 Month Business CD', 'ICS Shadow - Business - Demand',
       'Simple Business Checking', 'Business Checking',
       '1 Year Business CD', 'Business Elite Money Market',
       '3 Month Business CD', 'Business Money Market',
       '1st Choice Business Checking', 'Business Select High Yield',
       '9 Month Business CD', 'Community Assoc Reserve',
       '5 Year Business CD'], dtype=object)

In [20]:
df_filtered = df_filtered.sort_values(by='contractdate')